version: '3.7'

services:
  mongodb:
    image: mongo:4.2
    restart: always
    ports:
      - "27017:27017"
    init: true
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongodb_example
      - MONGO_INITDB_ROOT_PASSWORD=pass
      - MONGO_INITDB_DATABASE=admin
  faker:
    image: risniking/faker:latest
    ports:
      - "8081:8080"