context:
  initializer:
    classes: com.example.policypoc.infrastructure.configurations.WebConfiguration
logentries:
  token: ~
logging:
  level:
    org:
      zalando:
        logbook: TRACE
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss.SSS} %highlight(%-5level) %magenta(%logger.%M) - %msg%n%rEx"
logbook:
  exclude:
    - /health
    - /favicon.ico
    - /metrics
management:
  endpoints:
    web:
      base-path: ~
      exposure:
        include: health,metrics
spring:
  profiles:
    active: local
  data:
    mongodb:
      uri: "mongodb://mongodb_example:pass@localhost/mongodb_example?retryWrites=true&w=majority&authSource=admin"
server:
  port: 8080
vendors:
  ph3a:
    url: "http://localhost:8081/ph3a"
  neoway:
    url: "http://localhost:8081/neoway"